FROM node:14-alpine
WORKDIR /usr/src/app

RUN npm install pm2 -g

COPY package.json .

COPY . .

RUN npm i
RUN npx tsc -p .

COPY ./dist .

EXPOSE 3000

CMD ["pm2-runtime","/usr/src/app/adapters/controllers/rest-api/restify/v1/index.js"]
