FROM node:14-alpine
WORKDIR /usr/src/app

COPY package.json .

RUN npm install tsc
RUN npm install pm2 -g

# RUN npm run build:prod
RUN tsc -p .
COPY ./dist .
EXPOSE 3000
CMD ["pm2-runtime","./adapters/controllers/rest-api/restify/v1/index.js"]


# #BUILD
# FROM node:latest
# WORKDIR /usr/src/app
# COPY package*.json ./
# COPY . .
# # RUN npm run build:prod
# RUN npx tsc

# ## this is stage two , where the app actually runs

# FROM node:latest

# WORKDIR /usr/src/app
# COPY package*.json ./
# RUN npm install pm2 -g
# RUN npm install --only=production
# COPY --from=0 /usr/src/app/dist ./dist
# EXPOSE 3000
# CMD ["pm2-runtime","./adapters/controllers/rest-api/restify/v1/index.js"]


