FROM node:latest

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

RUN npm install pm2 -g

RUN npm run build:prod

COPY ./dist .

EXPOSE 3000

CMD ["pm2-runtime","./adapters/controllers/rest-api/restify/v1/index.js"]
