version: '3.1'

services:
  winkelzoeker-api:
    image: winkelzoeker/winkelzoeker.api:head
    container_name: 'winkelzoeker-api'
    restart: always
    ports:
      - 3000:3000
    environment:
      - SERVER_PROTOCOL=${SERVER_PROTOCOL}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - API_PORT=${API_PORT}
      - NODE_ENV=${NODE_ENV}
      - BASE_URL=${BASE_URL}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
  winkelzoeker-front:
    image: winkelzoeker/winkelzoeker.front:head
    container_name: 'winkelzoeker-front'
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - winkelzoeker-api