FROM node:14-alpine AS winkelzoeker-api-builder

WORKDIR /usr/src/app

RUN npm uninstall -g tsc
RUN npm install -g typescript

COPY package.json .

COPY . .

RUN npm i
RUN tsc -p .

# Our Second stage, that creates an image for production
FROM node:14-alpine AS winkelzoeker-api-production
RUN npm install pm2 -g

WORKDIR /app

COPY --from=winkelzoeker-api-builder /usr/src/app/dist ./dist
COPY package* ./
RUN npm install --production
EXPOSE 3000
CMD ["pm2-runtime","/usr/src/app/dist/adapters/controllers/rest-api/restify/v1/index.js"]
