FROM node:14-alpine
WORKDIR /usr/src/app

RUN npm uninstall -g tsc
RUN npm install -g typescript

COPY package.json .

COPY . .

RUN npm i
RUN tsc -p .

COPY ./dist .

EXPOSE 3000

RUN npm install pm2 -g
CMD ["pm2-runtime","/usr/src/app/dist/adapters/controllers/rest-api/restify/v1/index.js"]
