version: '3.1'

services:

  mongo:
    image: mongo
    container_name: 'winkelzoeker-db'
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ./secrets/seed.js:/docker-entrypoint-initdb.d/seed.js:ro
  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
  winkelzoeker-api:
    image: winkelzoeker/winkelzoeker.api:head
    container_name: 'winkelzoeker-api'
    restart: always
    ports:
      - 3000:3000
    environment:
      - SERVER_PROTOCOL=${SERVER_PROTOCOL}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - API_PORT=${API_PORT}
      - NODE_ENV=${NODE_ENV}
      - BASE_URL=${BASE_URL}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    depends_on:
      - mongo
  winkelzoeker-front:
    image: winkelzoeker/winkelzoeker.front:head
    container_name: 'winkelzoeker-front'
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - winkelzoeker-api