name: "Main Build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 3.8
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build
      run: npm i
    - name: Unit test
      run: npm run test:unit
