name: "Build image"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm i
    - name: Unit test
      run: npm run test:unit
    # - name: Code coverage
    #   run: npm run test:coverage

    # - name: Build and Publish head Docker image
    #   uses: VaultVulp/gp-docker-action@1.1.7
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
    #     image-name: winkelzoeker/winkelzoeker-api # Provide Docker image name
    #     image-tag: head # Provide Docker image tag
    #     dockerfile: Dockerfile.yml
  build:
    - name: Build the latest Docker image
      id: docker_build
      run: docker build . --file Dockerfile.yml --tag winkelzoeker/winkelzoeker-api:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}